package com.usthe.dao.mapper;

import com.usthe.entity.bo.AuthRole;

public interface AuthRoleMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    int insert(AuthRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    int insertSelective(AuthRole record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    AuthRole selectByPrimaryKey(Integer id);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    int updateByPrimaryKeySelective(AuthRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    int updateByPrimaryKey(AuthRole record);
}