package com.usthe.dao.mapper;

import com.usthe.entity.bo.AuthAccountLog;

public interface AuthAccountLogMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_account_log
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_account_log
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    int insert(AuthAccountLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_account_log
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    int insertSelective(AuthAccountLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_account_log
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_account_log
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    AuthAccountLog selectByPrimaryKey(Integer id);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_account_log
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    int updateByPrimaryKeySelective(AuthAccountLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_account_log
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    int updateByPrimaryKey(AuthAccountLog record);
}