package com.usthe.dao.mapper;

import com.usthe.entity.bo.AuthRoleResource;

public interface AuthRoleResourceMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_resource
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_resource
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    int insert(AuthRoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_resource
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    int insertSelective(AuthRoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_resource
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    AuthRoleResource selectByPrimaryKey(Integer id);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_resource
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    int updateByPrimaryKeySelective(AuthRoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_resource
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    int updateByPrimaryKey(AuthRoleResource record);
}