package com.usthe.entity.bo;

import java.util.Date;

public class AuthRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_role.ID
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_role.CODE
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_role.NAME
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_role.STATUS
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    private Short status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_role.CREATE_TIME
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_role.UPDATE_TIME
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_role.ID
     *
     * @return the value of auth_role.ID
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_role.ID
     *
     * @param id the value for auth_role.ID
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_role.CODE
     *
     * @return the value of auth_role.CODE
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_role.CODE
     *
     * @param code the value for auth_role.CODE
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_role.NAME
     *
     * @return the value of auth_role.NAME
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_role.NAME
     *
     * @param name the value for auth_role.NAME
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_role.STATUS
     *
     * @return the value of auth_role.STATUS
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_role.STATUS
     *
     * @param status the value for auth_role.STATUS
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_role.CREATE_TIME
     *
     * @return the value of auth_role.CREATE_TIME
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_role.CREATE_TIME
     *
     * @param createTime the value for auth_role.CREATE_TIME
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_role.UPDATE_TIME
     *
     * @return the value of auth_role.UPDATE_TIME
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_role.UPDATE_TIME
     *
     * @param updateTime the value for auth_role.UPDATE_TIME
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}