package com.usthe.entity.bo;

import java.util.Date;

public class AuthUserRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user_role.ID
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user_role.USER_ID
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user_role.ROLE_ID
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user_role.CREATE_TIME
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user_role.UPDATE_TIME
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user_role.ID
     *
     * @return the value of auth_user_role.ID
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user_role.ID
     *
     * @param id the value for auth_user_role.ID
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user_role.USER_ID
     *
     * @return the value of auth_user_role.USER_ID
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user_role.USER_ID
     *
     * @param userId the value for auth_user_role.USER_ID
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user_role.ROLE_ID
     *
     * @return the value of auth_user_role.ROLE_ID
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user_role.ROLE_ID
     *
     * @param roleId the value for auth_user_role.ROLE_ID
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user_role.CREATE_TIME
     *
     * @return the value of auth_user_role.CREATE_TIME
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user_role.CREATE_TIME
     *
     * @param createTime the value for auth_user_role.CREATE_TIME
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user_role.UPDATE_TIME
     *
     * @return the value of auth_user_role.UPDATE_TIME
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user_role.UPDATE_TIME
     *
     * @param updateTime the value for auth_user_role.UPDATE_TIME
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}