package com.usthe.entity.bo;

import java.util.Date;

public class AuthOperationLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_operation_log.ID
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_operation_log.LOG_NAME
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    private String logName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_operation_log.USER_ID
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_operation_log.API
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    private String api;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_operation_log.METHOD
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    private String method;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_operation_log.CREATE_TIME
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_operation_log.SUCCEED
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    private Byte succeed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_operation_log.MESSAGE
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    private String message;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_operation_log.ID
     *
     * @return the value of auth_operation_log.ID
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_operation_log.ID
     *
     * @param id the value for auth_operation_log.ID
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_operation_log.LOG_NAME
     *
     * @return the value of auth_operation_log.LOG_NAME
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    public String getLogName() {
        return logName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_operation_log.LOG_NAME
     *
     * @param logName the value for auth_operation_log.LOG_NAME
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    public void setLogName(String logName) {
        this.logName = logName == null ? null : logName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_operation_log.USER_ID
     *
     * @return the value of auth_operation_log.USER_ID
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_operation_log.USER_ID
     *
     * @param userId the value for auth_operation_log.USER_ID
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_operation_log.API
     *
     * @return the value of auth_operation_log.API
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    public String getApi() {
        return api;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_operation_log.API
     *
     * @param api the value for auth_operation_log.API
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    public void setApi(String api) {
        this.api = api == null ? null : api.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_operation_log.METHOD
     *
     * @return the value of auth_operation_log.METHOD
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_operation_log.METHOD
     *
     * @param method the value for auth_operation_log.METHOD
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    public void setMethod(String method) {
        this.method = method == null ? null : method.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_operation_log.CREATE_TIME
     *
     * @return the value of auth_operation_log.CREATE_TIME
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_operation_log.CREATE_TIME
     *
     * @param createTime the value for auth_operation_log.CREATE_TIME
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_operation_log.SUCCEED
     *
     * @return the value of auth_operation_log.SUCCEED
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    public Byte getSucceed() {
        return succeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_operation_log.SUCCEED
     *
     * @param succeed the value for auth_operation_log.SUCCEED
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    public void setSucceed(Byte succeed) {
        this.succeed = succeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_operation_log.MESSAGE
     *
     * @return the value of auth_operation_log.MESSAGE
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_operation_log.MESSAGE
     *
     * @param message the value for auth_operation_log.MESSAGE
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }
}