package com.usthe.entity.bo;

import java.util.Date;

public class AuthUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user.uid
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user.username
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user.password
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user.salt
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    private String salt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user.real_name
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    private String realName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user.avatar
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user.phone
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user.email
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user.sex
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    private Byte sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user.status
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user.CREATE_TIME
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user.UPDATE_TIME
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user.CREATE_WHERE
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    private Byte createWhere;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user.uid
     *
     * @return the value of auth_user.uid
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user.uid
     *
     * @param uid the value for auth_user.uid
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user.username
     *
     * @return the value of auth_user.username
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user.username
     *
     * @param username the value for auth_user.username
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user.password
     *
     * @return the value of auth_user.password
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user.password
     *
     * @param password the value for auth_user.password
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user.salt
     *
     * @return the value of auth_user.salt
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user.salt
     *
     * @param salt the value for auth_user.salt
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user.real_name
     *
     * @return the value of auth_user.real_name
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user.real_name
     *
     * @param realName the value for auth_user.real_name
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user.avatar
     *
     * @return the value of auth_user.avatar
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user.avatar
     *
     * @param avatar the value for auth_user.avatar
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user.phone
     *
     * @return the value of auth_user.phone
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user.phone
     *
     * @param phone the value for auth_user.phone
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user.email
     *
     * @return the value of auth_user.email
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user.email
     *
     * @param email the value for auth_user.email
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user.sex
     *
     * @return the value of auth_user.sex
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    public Byte getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user.sex
     *
     * @param sex the value for auth_user.sex
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    public void setSex(Byte sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user.status
     *
     * @return the value of auth_user.status
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user.status
     *
     * @param status the value for auth_user.status
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user.CREATE_TIME
     *
     * @return the value of auth_user.CREATE_TIME
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user.CREATE_TIME
     *
     * @param createTime the value for auth_user.CREATE_TIME
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user.UPDATE_TIME
     *
     * @return the value of auth_user.UPDATE_TIME
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user.UPDATE_TIME
     *
     * @param updateTime the value for auth_user.UPDATE_TIME
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user.CREATE_WHERE
     *
     * @return the value of auth_user.CREATE_WHERE
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    public Byte getCreateWhere() {
        return createWhere;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user.CREATE_WHERE
     *
     * @param createWhere the value for auth_user.CREATE_WHERE
     *
     * @mbg.generated Mon Apr 20 13:14:00 CST 2020
     */
    public void setCreateWhere(Byte createWhere) {
        this.createWhere = createWhere;
    }
}